# API-first development with OpenAPI
# This file will be used at compile time to generate Spring-MVC endpoint stubs using openapi-generator
openapi: '3.0.1'
info:
  title: 'ppa-batch-mcs'
  version: 0.0.1
servers:
  - url: http://localhost:9096/api
    description: Development server
  - url: https://localhost:9096/api
    description: Development server with TLS Profile
paths: {}
components:
  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
    basic:
      type: http
      description: Basic Authentication
      scheme: basic
security:
  - jwt: []
  - basic: []
